# Generated by Django 4.2.4 on 2023-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingstype',
            name='user',
        ),
        migrations.AddField(
            model_name='savingstype',
            name='user_id',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
